import assert from 'node:assert/strict';
import { test, describe } from 'node:test';
import { readFileSync } from 'node:fs';
import { join, resolve, win32 } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';
import {
  CLI_ENTRY,
  PROJECT_ROOT,
  createTempWorkspace,
  fromFileUrl,
  importLocalModule,
  removeTempWorkspace,
  toFileUrl,
  writeLocalModule,
} from './helpers/platform.js';

/**
 * Cross-platform file URL regression suite.
 *
 * Reproduces (in a platform-independent way) the Windows-only failure that used
 * to break the suite:
 *
 *   TypeError [ERR_INVALID_URL]: Invalid URL
 *   input: 'file://C:UsersIkyRuko-agentdistindex.js'
 *
 * Root cause chain:
 *   1. `'file://' + 'C:\\Users\\Iky\\Ruko-agent\\dist\\index.js'` is not a valid
 *      file URL (the drive letter would become the URL *host*).
 *   2. That string was injected into a generated `.mjs` script through a
 *      template literal, where every Windows backslash (`\U`, `\I`, `\R`,
 *      `\d`, `\i`) was swallowed as a JS escape — producing the malformed input
 *      above at runtime, on the machine only, with no error on POSIX.
 *   3. `await import(<malformed>)` then threw ERR_INVALID_URL.
 *
 * These tests pass on Linux/macOS *and* Windows, so the cloud matrix
 * (ubuntu + windows + macos) detects a regression on whichever OS it lands.
 */
describe('Cross-platform file URL construction (Windows ERR_INVALID_URL regression)', () => {
  test('toFileUrl() produces an absolute, round-trippable URL for the CLI entry', () => {
    const url = toFileUrl(CLI_ENTRY);

    assert.equal(new URL(url).protocol, 'file:', `expected a file: URL, got ${url}`);
    assert.ok(url.startsWith('file://'), `file URLs must be absolute, got ${url}`);
    assert.equal(url.includes('\\'), false, `file URL must not contain a raw backslash: ${url}`);
    assert.equal(url.includes(' '), false, `file URL must percent-encode spaces: ${url}`);
    assert.equal(
      resolve(fromFileUrl(url)),
      resolve(CLI_ENTRY),
      'fileURLToPath(toFileUrl(p)) must return the original path on every OS',
    );
    assert.equal(fileURLToPath(url), resolve(CLI_ENTRY));
  });

  test('the historical malformed string is rejected by the URL parser', () => {
    // Exactly the input reported by the Windows run (backslashes stripped).
    const malformed = 'file://C:UsersIkyRuko-agentdistindex.js';
    const isInvalidUrlError = (err: unknown): boolean =>
      (err as NodeJS.ErrnoException | null)?.code === 'ERR_INVALID_URL';

    assert.throws(() => new URL(malformed), isInvalidUrlError, 'malformed file URL must never parse');
    assert.throws(() => fileURLToPath(malformed), isInvalidUrlError, 'malformed file URL must never convert to a path');
  });

  test('naive "file://" + path concatenation corrupts real paths; pathToFileURL() does not', () => {
    // Spaces, "#" and "%" are legal in Windows %TEMP% / user profiles and in
    // POSIX temp dirs — they are exactly what the naive concatenation destroys.
    const ws = createTempWorkspace('ruko url#space test-');
    try {
      const target = join(ws, 'mod ule#%.mjs');
      const naive = 'file://' + target;

      let naiveRoundTrips = false;
      try {
        naiveRoundTrips = resolve(fileURLToPath(naive)) === resolve(target);
      } catch {
        naiveRoundTrips = false;
      }
      assert.equal(
        naiveRoundTrips,
        false,
        `naive "file://" + path must never be trusted (got ${naive}, want the real path ${target})`,
      );

      // The supported construction survives the same hostile path.
      const good = toFileUrl(target);
      assert.equal(resolve(fromFileUrl(good)), resolve(target));
      assert.ok(good.includes('%20'), `spaces must be percent-encoded in ${good}`);
      assert.ok(good.includes('%23'), `"#" must be percent-encoded in ${good}`);
      assert.ok(good.includes('%25'), `"%" must be percent-encoded in ${good}`);
      assert.equal(good.includes('\\'), false);
    } finally {
      removeTempWorkspace(ws);
    }
  });

  test('a generated .mjs mock imports through pathToFileURL() on every OS (yolo_hardening pattern)', async () => {
    const ws = createTempWorkspace('ruko tty#mock unicode-ü-');
    try {
      const payload = `ok-${process.platform}-${process.arch}`;
      // Same shape as the mock script generated by yolo_hardening.test.ts.
      const source = `export default ${JSON.stringify(payload)};\n`;
      const { path: modulePath, url } = writeLocalModule(ws, 'test tty#mock.mjs', source);

      assert.ok(url.startsWith('file://'));
      assert.equal(url.includes('\\'), false, `generated module URL must be backslash-free: ${url}`);
      assert.ok(url.includes('%20'), 'space in the temp path must stay encoded');

      const viaHelper = await importLocalModule<{ default: string }>(modulePath);
      assert.equal(viaHelper.default, payload);

      const viaUrl = (await import(url)) as { default: string };
      assert.equal(viaUrl.default, payload);
    } finally {
      removeTempWorkspace(ws);
    }
  });

  test('raw interpolation eats Windows separators; JSON.stringify injection does not', async () => {
    // Second half of the root cause: `'${winPath}'` inside a template literal
    // is re-parsed as JS in the generated module, so every backslash becomes an
    // escape (\U, \I, \T, \r, ...) and the separators vanish:
    //   C:\Users\Iky\...\dist\index.js  →  C:UsersIky...distindex.js
    // That mangled string is what produced `file://C:UsersIkyRuko-agentdistindex.js`.
    const winPath = 'C:\\Users\\Iky\\AppData\\Local\\Temp\\ruko\\dist\\index.js';
    const ws = createTempWorkspace('ruko escape#check-');
    try {
      const broken = writeLocalModule(ws, 'broken.mjs', `export default '${winPath}';\n`);
      const brokenValue = (await importLocalModule<{ default: string }>(broken.path)).default;
      assert.notEqual(brokenValue, winPath, 'raw interpolation must never be used to embed a path');
      assert.equal(brokenValue.includes('\\'), false, 'backslashes are consumed as JS escapes');

      const safe = writeLocalModule(ws, 'safe.mjs', `export default ${JSON.stringify(winPath)};\n`);
      const safeValue = (await importLocalModule<{ default: string }>(safe.path)).default;
      assert.equal(safeValue, winPath, 'JSON.stringify injection keeps the path byte-exact on every OS');
    } finally {
      removeTempWorkspace(ws);
    }
  });

  test('the CLI entry itself is importable through its file URL', async () => {
    // Static import of a side-effect module would run the CLI, so this only
    // verifies URL validity + readability (the dynamic-import path used by the
    // mock is covered above).
    const url = toFileUrl(CLI_ENTRY);
    const source = readFileSync(fileURLToPath(url), 'utf8');
    assert.ok(source.length > 0, 'CLI entry must be readable via its file URL');
    assert.ok(CLI_ENTRY.startsWith(PROJECT_ROOT), 'CLI entry must live inside the repository');
  });

  test(
    'win32 drive-letter and UNC paths become valid, round-trippable file URLs',
    { skip: process.platform !== 'win32' },
    () => {
      // Real Windows temp path — this is the one that broke: it contains the
      // user profile (spaces are common: "C:\Users\Iky R\AppData\Local\Temp").
      const tempDir = process.env.TEMP ?? process.env.TMP ?? 'C:\\Users\\Iky\\AppData\\Local\\Temp';
      const drivePath = join(tempDir, 'ruko dist', 'index.js');
      const driveUrl = toFileUrl(drivePath);

      assert.match(driveUrl, /^file:\/\/\/[A-Za-z]:\//, `drive URLs must be file:///C:/..., got ${driveUrl}`);
      assert.equal(new URL(driveUrl).host, '', 'the drive letter must never become the URL host');
      assert.equal(driveUrl.includes('\\'), false, 'URL must not leak Windows separators');
      assert.equal(driveUrl.includes(' '), false, 'spaces in %TEMP% must be percent-encoded');
      // The invariant that the old concatenation broke: URL → path → URL is stable.
      assert.equal(win32.resolve(fileURLToPath(driveUrl)), win32.resolve(drivePath));
      assert.equal(toFileUrl(fileURLToPath(driveUrl)), driveUrl);

      // UNC share: \\server\share\dist\index.js
      const unc = '\\\\server\\share\\dist\\index.js';
      const uncUrl = pathToFileURL(unc).href;
      assert.equal(new URL(uncUrl).protocol, 'file:', `unexpected UNC URL: ${uncUrl}`);
      assert.equal(uncUrl.includes('\\'), false, 'URL must not leak UNC separators');
      assert.ok(uncUrl.includes('server'), `UNC server must survive encoding: ${uncUrl}`);
      assert.equal(fileURLToPath(uncUrl), unc);
    },
  );
});
